In [45]:
import kaggle

In [46]:
#To download dataset from Kaggle in Python using Kaggle API:

In [47]:
# Download customer file directly
!kaggle datasets download rahulkumar37841/customer-purchase-behaviour-dataset -f customer.csv

Dataset URL: https://www.kaggle.com/datasets/rahulkumar37841/customer-purchase-behaviour-dataset
License(s): CC0-1.0
customer.csv: Skipping, found more recently modified local copy (use --force to force download)

In [48]:
import pandas as pd

In [49]:


import pandas as pd

# Load the files
df_customer = pd.read_csv('customer.csv')

# Use print() to display both outputs in the same cell
print("Customer Dataset:")
display(df_customer.head())

Customer Dataset:

,Customer ID,Age,Gender,Subscription Status,Previous Purchases,Frequency of Purchases,Location
0,2701,22,Female,No,36.0,Weekly,California
1,521,51,Male,Yes,20.0,Quarterly,South Carolina
2,3157,18,Female,NaN,18.0,Monthly,Montana
3,1687,22,Male,No,25.0,Annually,Illinois
4,2929,40,Female,No,17.0,Weekly,Alabama

In [50]:
df_customer

,Customer ID,Age,Gender,Subscription Status,Previous Purchases,Frequency of Purchases,Location
0,2701,22,Female,No,36.0,Weekly,California
1,521,51,Male,Yes,20.0,Quarterly,South Carolina
2,3157,18,Female,NaN,18.0,Monthly,Montana
3,1687,22,Male,No,25.0,Annually,Illinois
4,2929,40,Female,No,17.0,Weekly,Alabama
...,...,...,...,...,...,...,...
5045,913,24,Male,Yes,32.0,Monthly,Arkansas
5046,3466,19,Female,No,31.0,Weekly,Iowa
5047,3572,70,Female,No,15.0,Every 3 Months,North Dakota
5048,3195,43,Female,NaN,10.0,Bi-Weekly,Maryland
5049,1832,62,Male,No,5.0,Every 3 Months,Maine

In [51]:
df_customer.tail()

,Customer ID,Age,Gender,Subscription Status,Previous Purchases,Frequency of Purchases,Location
5045,913,24,Male,Yes,32.0,Monthly,Arkansas
5046,3466,19,Female,No,31.0,Weekly,Iowa
5047,3572,70,Female,No,15.0,Every 3 Months,North Dakota
5048,3195,43,Female,NaN,10.0,Bi-Weekly,Maryland
5049,1832,62,Male,No,5.0,Every 3 Months,Maine

In [52]:
len(df_customer)

5050

In [53]:
df_customer.shape

(5050, 7)

In [54]:
df_customer.describe(include="all")

,Customer ID,Age,Gender,Subscription Status,Previous Purchases,Frequency of Purchases,Location
count,5050.000000,5050.000000,5050,5017,4502.000000,5040,5050
unique,NaN,NaN,3,4,NaN,7,54
top,NaN,NaN,Male,No,NaN,Monthly,New York
freq,NaN,NaN,3018,3438,NaN,941,337
mean,2519.570891,44.150495,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,50.000000,NaN,NaN

In [55]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   str
 3   Subscription Status     5017 non-null   str
 4   Previous Purchases      4502 non-null   float64
 5   Frequency of Purchases  5040 non-null   str
 6   Location                5050 non-null   str
dtypes: float64(1), int64(2), str(4)
memory usage: 276.3 KB

In [56]:
#checking the null count
df_customer.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Subscription Status        33
Previous Purchases        548
Frequency of Purchases     10
Location                    0
dtype: int64

In [57]:
# Create a summary DataFrame
null_info = pd.DataFrame({
    'Null Count': df_customer.isnull().sum(),
    'Data Type': df_customer.dtypes
})

# Filter to show only columns that have at least one null value
null_info[null_info['Null Count'] > 0]

                        Null Count Data Type
Subscription Status             33       str
Previous Purchases             548   float64
Frequency of Purchases          10       str

In [58]:
# Check unique values in columns with nulls to see if they look like placeholders
print("Unique values in Subscription Status:", df_customer['Subscription Status'].unique())

Unique values in Subscription Status: <StringArray>
['No', 'Yes', nan, 'na', 'not available']
Length: 5, dtype: str

In [59]:
import numpy as np

# Convert 'na' and 'not available' to actual NaN
df_customer['Subscription Status'] = df_customer['Subscription Status'].replace(['na', 'not available'], np.nan)

In [60]:
# Check unique values in columns with nulls to see if they look like placeholders
print("Unique values in Subscription Status:", df_customer['Subscription Status'].unique())

Unique values in Subscription Status: <StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

In [62]:
# Fill 'Subscription Status' with the most frequent value (Mode)
mode_sub = df_customer['Subscription Status'].mode()[0]
df_customer['Subscription Status'] = df_customer['Subscription Status'].fillna(mode_sub)

In [63]:
print("Unique values in Subscription Status:", df_customer['Subscription Status'].unique())

Unique values in Subscription Status: <StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [35]:
print("Unique values in Previous Purchases:", df_customer['Previous Purchases'].unique())

Unique values in Previous Purchases: [36. 20. 18. 25. 17. 15.  2. 28.  7. 41.  4. nan 30. 33. 39. 13.  6. 50.
 24.  8.  5. 45. 31. 16. 47. 37.  1. 34. 12.  0.  9. 27. 40. 26. 32. 48.
 38. 22. 29. 11. 44. 35. 19. 10. 14.  3. 49. 46. 43. 42. 21. 23.]

In [66]:
# Filling Previous Purchases with Zero(0)
df_customer['Previous Purchases']=df_customer['Previous Purchases'].fillna(0)

In [67]:
print("Unique values in Previous Purchases:", df_customer['Previous Purchases'].unique())

Unique values in Previous Purchases: [36. 20. 18. 25. 17. 15.  2. 28.  7. 41.  4.  0. 30. 33. 39. 13.  6. 50.
 24.  8.  5. 45. 31. 16. 47. 37.  1. 34. 12.  9. 27. 40. 26. 32. 48. 38.
 22. 29. 11. 44. 35. 19. 10. 14.  3. 49. 46. 43. 42. 21. 23.]

In [69]:
print("Unique values in Frequency of Purchases:", df_customer['Frequency of Purchases'].unique())

Unique values in Frequency of Purchases: <StringArray>
[        'Weekly',      'Quarterly',        'Monthly',       'Annually',
 'Every 3 Months',      'Bi-Weekly',    'Fortnightly',              nan]
Length: 8, dtype: str

In [71]:
# Fill with a new category
df_customer['Frequency of Purchases'] = df_customer['Frequency of Purchases'].fillna('Unknown')

In [72]:
# Create a summary DataFrame
null_info = pd.DataFrame({
    'Null Count': df_customer.isnull().sum(),
    'Data Type': df_customer.dtypes
})

# Filter to show only columns that have at least one null value
null_info[null_info['Null Count'] > 0]

Empty DataFrame
Columns: [Null Count, Data Type]
Index: []

In [73]:
df_customer.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Subscription Status       0
Previous Purchases        0
Frequency of Purchases    0
Location                  0
dtype: int64

In [74]:
# renaming the headers

In [77]:
df_customer.columns=df_customer.columns.str.replace(" ","_")
df_customer.columns=df_customer.columns.str.lower()

In [81]:
df_customer.columns

Index(['customer_id', 'age', 'gender', 'subscription_status',
       'previous_purchases', 'frequency_of_purchases', 'location'],
      dtype='str')

In [82]:
df_customer .head()

,customer_id,age,gender,subscription_status,previous_purchases,frequency_of_purchases,location
0,2701,22,Female,No,36.0,Weekly,California
1,521,51,Male,Yes,20.0,Quarterly,South Carolina
2,3157,18,Female,No,18.0,Monthly,Montana
3,1687,22,Male,No,25.0,Annually,Illinois
4,2929,40,Female,No,17.0,Weekly,Alabama

In [83]:
# Final confirmation of your cleaned dataset
print("Dataset successfully cleaned!")
print(f"Final shape: {df_customer.shape[0]} rows and {df_customer.shape[1]} columns")

# Display the head to verify the final format
display(df_customer.head())

Dataset successfully cleaned!
Final shape: 5040 rows and 7 columns

,customer_id,age,gender,subscription_status,previous_purchases,frequency_of_purchases,location
0,2701,22,Female,No,36.0,Weekly,California
1,521,51,Male,Yes,20.0,Quarterly,South Carolina
2,3157,18,Female,No,18.0,Monthly,Montana
3,1687,22,Male,No,25.0,Annually,Illinois
4,2929,40,Female,No,17.0,Weekly,Alabama

In [87]:
 # Save it for your SQL work
df_customer.to_csv('cleaned_customer.csv', index=False)
print("\nCleaned dataset saved as 'cleaned_customer.csv'")

Cleaned dataset saved as 'cleaned_customer.csv'